# Generated by Django 5.2.3 on 2025-06-30 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_agency', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=50)),
                ('official_id', models.FileField(upload_to='admin_ids/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('national_id_number', models.CharField(max_length=20)),
                ('id_document', models.FileField(upload_to='citizen_ids/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('cac_number', models.CharField(max_length=50)),
                ('tax_id_number', models.CharField(max_length=50)),
                ('company_address', models.TextField()),
                ('industry_type', models.CharField(max_length=100)),
                ('cac_certificate', models.FileField(upload_to='org_docs/')),
                ('tax_clearance_certificate', models.FileField(upload_to='org_docs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
