# Generated by Django 5.2.3 on 2025-07-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizationprofile_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='organization_id',
        ),
    ]
