# Generated by Django 5.2.3 on 2025-07-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('personal_data', 'Personal Data'), ('transaction_history', 'Transaction History'), ('account_details', 'Account Details'), ('all_data', 'All Data')], max_length=50)),
                ('reason', models.TextField(help_text='Reason for data request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='data_exports/')),
                ('download_expires_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='accounts.adminprofile')),
                ('citizen', models.ForeignKey(limit_choices_to={'groups__name': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='accounts.citizenprofile')),
                ('company', models.ForeignKey(limit_choices_to={'groups__name': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.organizationprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.adminprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='request_app.datarequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
