# Generated by Django 5.2.3 on 2025-07-09 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_app', '0002_alter_datarequest_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequest',
            name='company',
        ),
        migrations.AlterField(
            model_name='datarequest',
            name='citizen',
            field=models.ForeignKey(limit_choices_to={'user_type': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
